import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  Table, TableRow, TableCell, WidthType, AlignmentType, BorderStyle,
} from "docx";
import { saveAs } from "file-saver";

const stripMarkdown = (text: string) =>
  text
    .replace(/!\[.*?\]\(.*?\)/g, "")
    .replace(/\[(.*?)\]\(.*?\)/g, "$1")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/__(.*?)__/g, "$1")
    .replace(/_(.*?)_/g, "$1")
    .replace(/`(.*?)`/g, "$1")
    .replace(/^---$/g, "")
    .trim();

const safeName = (title: string) =>
  (title || "Untitled").replace(/[^a-zA-Z0-9-_]+/g, "_").slice(0, 80);

export async function exportToPDF(title: string, content: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;
  const footerHeight = 15;
  const contentBottomMargin = margin + footerHeight;

  let cursorY = 20;

  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      const date = new Date().toLocaleDateString();
      const footerText = `Generated by DocuForge AI on ${date} | Page ${i} of ${pageCount}`;
      doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: "center" });
    }
  };

  const checkPageBreak = (neededHeight: number) => {
    if (cursorY + neededHeight > pageHeight - contentBottomMargin) {
      doc.addPage();
      cursorY = margin;
    }
  };

  // Cover page
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(10, 25, 47);
  const titleLines = doc.splitTextToSize(title || "Untitled Document", maxLineWidth);
  doc.text(titleLines, pageWidth / 2, 60, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, 80, { align: "center" });
  doc.addPage();
  cursorY = margin;

  const lines = content.split("\n");
  let i = 0;

  while (i < lines.length) {
    const raw = lines[i];
    const line = raw.trim();

    if (!line) {
      cursorY += 4;
      i++;
      continue;
    }

    if (line === "---" || line === "***" || line === "___") {
      doc.addPage();
      cursorY = margin;
      i++;
      continue;
    }

    // Tables
    if (line.includes("|") && lines[i + 1]?.includes("|")) {
      const isSeparator = (l: string) => l.includes("|") && /[-:]/.test(l) && !/[a-zA-Z0-9]{2,}/.test(l.replace(/[|\-:\s]/g, ""));
      if (isSeparator(lines[i + 1])) {
        const headers = line.split("|").filter((c) => c.trim()).map((c) => stripMarkdown(c));
        i += 2;
        const tableRows: string[][] = [];
        while (i < lines.length && lines[i].includes("|")) {
          if (!isSeparator(lines[i])) {
            const row = lines[i].split("|").filter((c) => c.trim()).map((c) => stripMarkdown(c));
            if (row.length > 0) tableRows.push(row);
          }
          i++;
        }
        autoTable(doc, {
          head: [headers],
          body: tableRows,
          startY: cursorY,
          margin: { left: margin, right: margin },
          styles: { fontSize: 9, cellPadding: 2, textColor: [33, 33, 33] },
          headStyles: { fillColor: [10, 25, 47], textColor: 255, fontStyle: "bold" },
          alternateRowStyles: { fillColor: [245, 247, 250] },
        });
        cursorY = (doc as any).lastAutoTable.finalY + 8;
        continue;
      }
    }

    // Code block
    if (line.startsWith("```")) {
      i++;
      const codeLines: string[] = [];
      while (i < lines.length && !lines[i].trim().startsWith("```")) {
        codeLines.push(lines[i]);
        i++;
      }
      i++; // skip closing fence
      doc.setFont("courier", "normal");
      doc.setFontSize(9);
      doc.setTextColor(40, 40, 40);
      checkPageBreak(codeLines.length * 4 + 6);
      // Background
      const blockHeight = codeLines.length * 4 + 4;
      doc.setFillColor(245, 247, 250);
      doc.rect(margin - 2, cursorY - 3, maxLineWidth + 4, blockHeight, "F");
      codeLines.forEach((cl) => {
        const split = doc.splitTextToSize(cl, maxLineWidth - 4);
        split.forEach((s: string) => {
          checkPageBreak(5);
          doc.text(s, margin, cursorY);
          cursorY += 4;
        });
      });
      cursorY += 6;
      continue;
    }

    // Headings
    if (line.startsWith("#")) {
      let level = 0;
      let headingText = line;
      while (headingText.startsWith("#")) {
        level++;
        headingText = headingText.substring(1);
      }
      headingText = stripMarkdown(headingText.trim());

      let fontSize = 11;
      if (level === 1) { fontSize = 18; cursorY += 8; }
      else if (level === 2) { fontSize = 14; cursorY += 6; }
      else if (level === 3) { fontSize = 12; cursorY += 4; }
      else { fontSize = 11; cursorY += 2; }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(fontSize);
      doc.setTextColor(10, 25, 47);
      const split = doc.splitTextToSize(headingText, maxLineWidth);
      checkPageBreak(split.length * (fontSize * 0.5) + 6);
      doc.text(split, margin, cursorY);
      cursorY += split.length * (fontSize * 0.5) + 6;
      i++;
      continue;
    }

    // Lists
    if (line.startsWith("* ") || line.startsWith("- ") || line.startsWith("•") || /^\d+\.\s/.test(line)) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(33, 33, 33);
      const isNum = /^\d+\.\s/.exec(line);
      const bullet = isNum ? isNum[0] : "•";
      const text = line.replace(/^([*•-]\s*|\d+\.\s*)/, "");
      const cleanText = stripMarkdown(text);
      if (cleanText) {
        const split = doc.splitTextToSize(cleanText, maxLineWidth - 12);
        checkPageBreak(split.length * 5 + 2);
        doc.text(bullet, margin, cursorY);
        doc.text(split, margin + 10, cursorY);
        cursorY += split.length * 5 + 2;
      }
      i++;
      continue;
    }

    // Paragraph
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(33, 33, 33);
    const text = stripMarkdown(line);
    if (text) {
      const split = doc.splitTextToSize(text, maxLineWidth);
      checkPageBreak(split.length * 5 + 4);
      doc.text(split, margin, cursorY);
      cursorY += split.length * 5 + 4;
    }
    i++;
  }

  addFooter();
  const blob = doc.output("blob");
  saveAs(blob, `${safeName(title)}_Documentation.pdf`);
}

function parseInline(text: string): TextRun[] {
  const runs: TextRun[] = [];
  const cleaned = text.replace(/`(.*?)`/g, "$1");
  const regex = /(\*\*(.+?)\*\*|\*(.+?)\*|__(.+?)__|_(.+?)_)/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = regex.exec(cleaned)) !== null) {
    if (m.index > last) runs.push(new TextRun(cleaned.slice(last, m.index)));
    const bold = m[2] || m[4];
    const italic = m[3] || m[5];
    if (bold) runs.push(new TextRun({ text: bold, bold: true }));
    else if (italic) runs.push(new TextRun({ text: italic, italics: true }));
    last = m.index + m[0].length;
  }
  if (last < cleaned.length) runs.push(new TextRun(cleaned.slice(last)));
  return runs.length ? runs : [new TextRun(cleaned)];
}

function buildDocxChildren(content: string): (Paragraph | Table)[] {
  const out: (Paragraph | Table)[] = [];
  const lines = content.split("\n");
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      out.push(new Paragraph({ children: [new TextRun("")] }));
      i++;
      continue;
    }

    if (trimmed === "---" || trimmed === "***") {
      out.push(new Paragraph({ children: [new TextRun({ text: "" })], pageBreakBefore: true }));
      i++;
      continue;
    }

    // Tables
    if (trimmed.includes("|") && lines[i + 1]?.includes("|")) {
      const isSep = (l: string) => l.includes("|") && /[-:]/.test(l) && !/[a-zA-Z0-9]{2,}/.test(l.replace(/[|\-:\s]/g, ""));
      if (isSep(lines[i + 1])) {
        const headers = trimmed.split("|").filter((c) => c.trim()).map((c) => stripMarkdown(c));
        i += 2;
        const rows: string[][] = [];
        while (i < lines.length && lines[i].includes("|")) {
          if (!isSep(lines[i])) {
            const row = lines[i].split("|").filter((c) => c.trim()).map((c) => stripMarkdown(c));
            if (row.length > 0) rows.push(row);
          }
          i++;
        }
        const headerRow = new TableRow({
          children: headers.map((h) => new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: "FFFFFF" })] })],
            shading: { fill: "0A192F" },
          })),
        });
        const bodyRows = rows.map((r, idx) => new TableRow({
          children: r.map((c) => new TableCell({
            children: [new Paragraph({ children: parseInline(c) })],
            shading: idx % 2 === 1 ? { fill: "F5F7FA" } : undefined,
          })),
        }));
        out.push(new Table({
          rows: [headerRow, ...bodyRows],
          width: { size: 100, type: WidthType.PERCENTAGE },
        }));
        out.push(new Paragraph({ children: [new TextRun("")] }));
        continue;
      }
    }

    // Code block
    if (trimmed.startsWith("```")) {
      i++;
      const codeLines: string[] = [];
      while (i < lines.length && !lines[i].trim().startsWith("```")) {
        codeLines.push(lines[i]);
        i++;
      }
      i++;
      codeLines.forEach((cl) => {
        out.push(new Paragraph({
          children: [new TextRun({ text: cl, font: "Courier New", size: 18 })],
          shading: { fill: "F5F7FA", type: "clear", color: "auto" },
        }));
      });
      continue;
    }

    // Headings
    if (trimmed.startsWith("#")) {
      let level = 0;
      let txt = trimmed;
      while (txt.startsWith("#")) { level++; txt = txt.substring(1); }
      txt = txt.trim();
      const headingMap: Record<number, (typeof HeadingLevel)[keyof typeof HeadingLevel]> = {
        1: HeadingLevel.HEADING_1,
        2: HeadingLevel.HEADING_2,
        3: HeadingLevel.HEADING_3,
        4: HeadingLevel.HEADING_4,
        5: HeadingLevel.HEADING_5,
        6: HeadingLevel.HEADING_6,
      };
      out.push(new Paragraph({
        children: parseInline(txt),
        heading: headingMap[level] || HeadingLevel.HEADING_6,
      }));
      i++;
      continue;
    }

    // Lists
    if (/^([*\-•]\s+|\d+\.\s+)/.test(trimmed)) {
      const isNum = /^\d+\./.test(trimmed);
      const text = trimmed.replace(/^([*•\-]\s+|\d+\.\s+)/, "");
      out.push(new Paragraph({
        children: parseInline(text),
        bullet: isNum ? undefined : { level: 0 },
        numbering: isNum ? { reference: "default-numbering", level: 0 } : undefined,
        indent: { left: 360 },
      }));
      i++;
      continue;
    }

    // Paragraph
    out.push(new Paragraph({
      children: parseInline(trimmed),
      spacing: { after: 160 },
    }));
    i++;
  }

  return out;
}

export async function exportToWord(title: string, content: string) {
  const doc = new Document({
    creator: "DocuForge AI",
    title,
    description: "Generated by DocuForge AI",
    numbering: {
      config: [{
        reference: "default-numbering",
        levels: [{
          level: 0,
          format: "decimal",
          text: "%1.",
          alignment: AlignmentType.START,
          style: { paragraph: { indent: { left: 360, hanging: 260 } } },
        }],
      }],
    },
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: title || "Untitled Document",
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            children: [new TextRun({ text: `Generated on ${new Date().toLocaleDateString()}`, italics: true, color: "666666" })],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          ...buildDocxChildren(content),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${safeName(title)}_Documentation.docx`);
}

export function exportToMarkdown(title: string, content: string) {
  const body = content.startsWith("#") ? content : `# ${title}\n\n${content}`;
  const blob = new Blob([body], { type: "text/markdown;charset=utf-8" });
  saveAs(blob, `${safeName(title)}_Documentation.md`);
}
